### ISSUE TITLE
Feature Request or missing Documentation?

### ISSUE THREAD

**Issue by neophob** [nolanlawson/optimize-js#10]
Hi, thanks for optimize-js. I would like to include it in my webpack workflow. Question:
- does a Webpack plugin already exists?
- is #7 an issue to create one if it does not already exists?

**Comment by vigneshshanmugam** [comment]
@neophob Yes it does. https://github.com/vigneshshanmugam/optimize-js-plugin 

Haven't tested it in production though.

**Comment by nolanlawson** [comment]
Thanks, gonna consider this closed since @vigneshshanmugam nailed it. #7 is something that needs to be fixed in core; we need to handle arrays of functions passed as an argument to a function as the same as functions passed as arguments to a function. Probably I didn't discover the Webpack problem because the scripts in my library are built with Browserify or other non-Webpack tools (or output by Webpack as UMD, not quite sure).
